/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.randommain.fastpaste;

public final class R {
  public static final class id {
    public static final int activity_main_button1=0x7f010000;
    public static final int hello_text=0x7f010001;
  }
  public static final class layout {
    public static final int activity_main=0x7f020000;
  }
  public static final class string {
    public static final int activity_main_button1=0x7f030000;
    public static final int app_name=0x7f030001;
    public static final int hello_msg=0x7f030002;
    public static final int menu_settings=0x7f030003;
    public static final int pressed=0x7f030004;
    public static final int title_activity_main=0x7f030005;
  }
}